package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

var ErrNotFound = errors.New("not found")

// Store is backed by Postgres. IDs, timestamps, and default values are
// generated by the database (see server/migrations/0001_init.up.sql); Go
// code never invents a resource ID.
type Store struct {
	pool *pgxpool.Pool
}

func NewStore(pool *pgxpool.Pool) *Store {
	return &Store{pool: pool}
}

// querier is satisfied by both *pgxpool.Pool and pgx.Tx, so helper
// functions (notably the dependency validators in validation.go) can run
// against either a bare pool call or inside an in-flight transaction
// without duplicating queries.
type querier interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

// --- Projects ---

type ProjectPatch struct {
	Name        *string        `json:"name"`
	Description *string        `json:"description"`
	Metadata    map[string]any `json:"metadata"`
}

func scanProject(row pgx.Row) (*Project, error) {
	p := &Project{}
	var metadata []byte
	if err := row.Scan(&p.ID, &p.Name, &p.Description, &metadata, &p.LastSeq, &p.CreatedAt, &p.UpdatedAt); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	if err := json.Unmarshal(metadata, &p.Metadata); err != nil {
		return nil, fmt.Errorf("decode project metadata: %w", err)
	}
	return p, nil
}

const projectColumns = `id::text, name, description, metadata, last_seq, created_at, updated_at`

func (s *Store) CreateProject(ctx context.Context, p *Project) (*Project, error) {
	if p.Metadata == nil {
		p.Metadata = map[string]any{}
	}
	metadata, err := json.Marshal(p.Metadata)
	if err != nil {
		return nil, fmt.Errorf("encode project metadata: %w", err)
	}
	row := s.pool.QueryRow(ctx, `
		INSERT INTO projects (name, description, metadata)
		VALUES ($1, $2, $3::jsonb)
		RETURNING `+projectColumns,
		p.Name, p.Description, metadata,
	)
	return scanProject(row)
}

func (s *Store) ListProjects(ctx context.Context) ([]*Project, error) {
	rows, err := s.pool.Query(ctx, `SELECT `+projectColumns+` FROM projects ORDER BY created_at`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*Project{}
	for rows.Next() {
		p, err := scanProject(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, p)
	}
	return out, rows.Err()
}

func (s *Store) GetProject(ctx context.Context, id string) (*Project, error) {
	row := s.pool.QueryRow(ctx, `SELECT `+projectColumns+` FROM projects WHERE id = $1::uuid`, id)
	return scanProject(row)
}

func (s *Store) UpdateProject(ctx context.Context, id string, patch ProjectPatch, actor string) (*Project, []StoredEvent, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return nil, nil, err
	}
	defer tx.Rollback(ctx)

	current, err := scanProject(tx.QueryRow(ctx, `SELECT `+projectColumns+` FROM projects WHERE id = $1::uuid FOR UPDATE`, id))
	if err != nil {
		return nil, nil, err
	}

	changes := map[string]any{}
	if patch.Name != nil {
		current.Name = *patch.Name
		changes["name"] = *patch.Name
	}
	if patch.Description != nil {
		current.Description = *patch.Description
		changes["description"] = *patch.Description
	}
	if patch.Metadata != nil {
		current.Metadata = patch.Metadata
		changes["metadata"] = patch.Metadata
	}
	metadata, err := json.Marshal(current.Metadata)
	if err != nil {
		return nil, nil, fmt.Errorf("encode project metadata: %w", err)
	}

	var events []StoredEvent
	if len(changes) > 0 {
		// Claim the seq and record the event before the final RETURNING
		// below, so the row it reads back already reflects the bumped
		// last_seq.
		ev, err := recordEvent(ctx, tx, id, EventProjectUpdated, ProjectUpdatedPayload{Changes: changes}, actor)
		if err != nil {
			return nil, nil, err
		}
		events = append(events, ev)
	}

	row := tx.QueryRow(ctx, `
		UPDATE projects SET name = $2, description = $3, metadata = $4::jsonb, updated_at = now()
		WHERE id = $1::uuid
		RETURNING `+projectColumns,
		id, current.Name, current.Description, metadata,
	)
	updated, err := scanProject(row)
	if err != nil {
		return nil, nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, nil, err
	}
	return updated, events, nil
}

func (s *Store) DeleteProject(ctx context.Context, id string) error {
	tag, err := s.pool.Exec(ctx, `DELETE FROM projects WHERE id = $1::uuid`, id)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// --- Tasks ---

type TaskPatch struct {
	Title         *string            `json:"title"`
	Status        *TaskStatus        `json:"status"`
	AssignedTo    []string           `json:"assignedTo"`
	Configuration *TaskConfiguration `json:"configuration"`
	Dependencies  []string           `json:"dependencies"`
}

const taskSelectBase = `
	SELECT t.id::text, t.project_id::text, t.title, t.status, t.assigned_to, t.configuration,
	       t.created_at, t.updated_at,
	       COALESCE(array_agg(td.depends_on_task_id::text) FILTER (WHERE td.depends_on_task_id IS NOT NULL), '{}')
	FROM tasks t
	LEFT JOIN task_dependencies td ON td.task_id = t.id`

func scanTask(row pgx.Row) (*Task, error) {
	t := &Task{}
	var configuration []byte
	if err := row.Scan(
		&t.ID, &t.ProjectID, &t.Title, &t.Status, &t.AssignedTo, &configuration,
		&t.CreatedAt, &t.UpdatedAt, &t.Dependencies,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	if err := json.Unmarshal(configuration, &t.Configuration); err != nil {
		return nil, fmt.Errorf("decode task configuration: %w", err)
	}
	if t.AssignedTo == nil {
		t.AssignedTo = []string{}
	}
	if t.Configuration.Tags == nil {
		t.Configuration.Tags = []string{}
	}
	if t.Configuration.CustomFields == nil {
		t.Configuration.CustomFields = map[string]any{}
	}
	return t, nil
}

func scanTasks(rows pgx.Rows) ([]*Task, error) {
	defer rows.Close()
	out := []*Task{}
	for rows.Next() {
		t, err := scanTask(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, t)
	}
	return out, rows.Err()
}

func (s *Store) CreateTask(ctx context.Context, t *Task, actor string) (*Task, []StoredEvent, error) {
	if t.Status == "" {
		t.Status = StatusTodo
	}
	if t.AssignedTo == nil {
		t.AssignedTo = []string{}
	}
	if t.Configuration.Tags == nil {
		t.Configuration.Tags = []string{}
	}
	if t.Configuration.CustomFields == nil {
		t.Configuration.CustomFields = map[string]any{}
	}
	configuration, err := json.Marshal(t.Configuration)
	if err != nil {
		return nil, nil, fmt.Errorf("encode task configuration: %w", err)
	}

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return nil, nil, err
	}
	defer tx.Rollback(ctx)

	// A brand-new task has no ID yet and can't already be anyone's
	// dependency, so a cycle is structurally impossible here — this still
	// checks existence/same-project/self-ref against the proposed deps.
	if err := validateDependencies(ctx, tx, "", t.ProjectID, t.Dependencies); err != nil {
		return nil, nil, err
	}

	row := tx.QueryRow(ctx, `
		INSERT INTO tasks (project_id, title, status, assigned_to, configuration)
		VALUES ($1::uuid, $2, $3, $4, $5::jsonb)
		RETURNING id::text`,
		t.ProjectID, t.Title, t.Status, t.AssignedTo, configuration,
	)
	var id string
	if err := row.Scan(&id); err != nil {
		return nil, nil, err
	}

	if err := insertDependencies(ctx, tx, id, t.Dependencies); err != nil {
		return nil, nil, err
	}

	created, err := scanTask(tx.QueryRow(ctx, taskSelectBase+` WHERE t.id = $1::uuid GROUP BY t.id`, id))
	if err != nil {
		return nil, nil, err
	}

	ev, err := recordEvent(ctx, tx, t.ProjectID, EventTaskCreated, TaskCreatedPayload{Task: created}, actor)
	if err != nil {
		return nil, nil, err
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, nil, err
	}
	return created, []StoredEvent{ev}, nil
}

func (s *Store) ListTasksByProject(ctx context.Context, projectID string) ([]*Task, error) {
	rows, err := s.pool.Query(ctx, taskSelectBase+` WHERE t.project_id = $1::uuid GROUP BY t.id ORDER BY t.created_at`, projectID)
	if err != nil {
		return nil, err
	}
	return scanTasks(rows)
}

func (s *Store) GetTask(ctx context.Context, id string) (*Task, error) {
	row := s.pool.QueryRow(ctx, taskSelectBase+` WHERE t.id = $1::uuid GROUP BY t.id`, id)
	return scanTask(row)
}

// UpdateTask applies patch to task id inside a transaction: dependency
// changes are validated against the live DB state, status transitions to
// "done" are blocked while any dependency is incomplete, and the row is
// locked for the duration so concurrent updates to the same task serialize
// instead of racing.
func (s *Store) UpdateTask(ctx context.Context, id string, patch TaskPatch, actor string) (*Task, []StoredEvent, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return nil, nil, err
	}
	defer tx.Rollback(ctx)

	// Lock the row with a plain SELECT first — Postgres doesn't allow FOR
	// UPDATE combined with GROUP BY — then load the full current state
	// (including dependencies) via the aggregate query.
	var locked string
	if err := tx.QueryRow(ctx, `SELECT id::text FROM tasks WHERE id = $1::uuid FOR UPDATE`, id).Scan(&locked); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil, ErrNotFound
		}
		return nil, nil, err
	}

	current, err := scanTask(tx.QueryRow(ctx, taskSelectBase+` WHERE t.id = $1::uuid GROUP BY t.id`, id))
	if err != nil {
		return nil, nil, err
	}

	deps := current.Dependencies
	if patch.Dependencies != nil {
		if err := validateDependencies(ctx, tx, id, current.ProjectID, patch.Dependencies); err != nil {
			return nil, nil, err
		}
		deps = patch.Dependencies
	}
	if patch.Status != nil && *patch.Status == StatusDone {
		if err := validateCanComplete(ctx, tx, deps); err != nil {
			return nil, nil, err
		}
	}

	// Only the fields actually present in the patch go into the
	// task.updated event's Changes map — dependencies are handled
	// separately below as their own task.dependencies_changed event, per
	// the confirmed design (one PATCH touching both scalar fields and
	// dependencies emits two events, two seq numbers).
	changes := map[string]any{}
	if patch.Title != nil {
		current.Title = *patch.Title
		changes["title"] = *patch.Title
	}
	if patch.Status != nil {
		current.Status = *patch.Status
		changes["status"] = *patch.Status
	}
	if patch.AssignedTo != nil {
		current.AssignedTo = patch.AssignedTo
		changes["assignedTo"] = patch.AssignedTo
	}
	if patch.Configuration != nil {
		current.Configuration = *patch.Configuration
		changes["configuration"] = *patch.Configuration
	}
	configuration, err := json.Marshal(current.Configuration)
	if err != nil {
		return nil, nil, fmt.Errorf("encode task configuration: %w", err)
	}

	if _, err := tx.Exec(ctx, `
		UPDATE tasks SET title = $2, status = $3, assigned_to = $4, configuration = $5::jsonb, updated_at = now()
		WHERE id = $1::uuid`,
		id, current.Title, current.Status, current.AssignedTo, configuration,
	); err != nil {
		return nil, nil, err
	}

	if patch.Dependencies != nil {
		if _, err := tx.Exec(ctx, `DELETE FROM task_dependencies WHERE task_id = $1::uuid`, id); err != nil {
			return nil, nil, err
		}
		if err := insertDependencies(ctx, tx, id, patch.Dependencies); err != nil {
			return nil, nil, err
		}
	}

	var events []StoredEvent
	if len(changes) > 0 {
		ev, err := recordEvent(ctx, tx, current.ProjectID, EventTaskUpdated, TaskUpdatedPayload{TaskID: id, Changes: changes}, actor)
		if err != nil {
			return nil, nil, err
		}
		events = append(events, ev)
	}
	if patch.Dependencies != nil {
		ev, err := recordEvent(ctx, tx, current.ProjectID, EventTaskDependenciesChanged, TaskDependenciesChangedPayload{TaskID: id, DependsOn: patch.Dependencies}, actor)
		if err != nil {
			return nil, nil, err
		}
		events = append(events, ev)
	}

	updated, err := scanTask(tx.QueryRow(ctx, taskSelectBase+` WHERE t.id = $1::uuid GROUP BY t.id`, id))
	if err != nil {
		return nil, nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, nil, err
	}
	return updated, events, nil
}

// DeleteTask removes a task; ON DELETE CASCADE takes care of its
// task_dependencies rows (both directions) and comments. The IDs of other
// tasks that depended on it are folded into the task.deleted event's
// RemovedFromDependenciesOf, rather than emitted as separate events —
// clients are expected to strip the deleted ID from those tasks' local
// dependency lists directly from that one event.
func (s *Store) DeleteTask(ctx context.Context, id string, actor string) (projectID string, events []StoredEvent, err error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return "", nil, err
	}
	defer tx.Rollback(ctx)

	if err := tx.QueryRow(ctx, `SELECT project_id::text FROM tasks WHERE id = $1::uuid FOR UPDATE`, id).Scan(&projectID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return "", nil, ErrNotFound
		}
		return "", nil, err
	}

	rows, err := tx.Query(ctx, `SELECT task_id::text FROM task_dependencies WHERE depends_on_task_id = $1::uuid`, id)
	if err != nil {
		return "", nil, err
	}
	affected := []string{}
	for rows.Next() {
		var affectedID string
		if err := rows.Scan(&affectedID); err != nil {
			rows.Close()
			return "", nil, err
		}
		affected = append(affected, affectedID)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return "", nil, err
	}

	if _, err := tx.Exec(ctx, `DELETE FROM tasks WHERE id = $1::uuid`, id); err != nil {
		return "", nil, err
	}

	ev, err := recordEvent(ctx, tx, projectID, EventTaskDeleted, TaskDeletedPayload{TaskID: id, RemovedFromDependenciesOf: affected}, actor)
	if err != nil {
		return "", nil, err
	}

	if err := tx.Commit(ctx); err != nil {
		return "", nil, err
	}
	return projectID, []StoredEvent{ev}, nil
}

// insertDependencies must run inside the same transaction as the
// validation that approved deps, so the two can't race against a
// concurrent change to the dependency graph.
func insertDependencies(ctx context.Context, tx pgx.Tx, taskID string, deps []string) error {
	for _, depID := range deps {
		if _, err := tx.Exec(ctx, `INSERT INTO task_dependencies (task_id, depends_on_task_id) VALUES ($1::uuid, $2::uuid)`, taskID, depID); err != nil {
			return err
		}
	}
	return nil
}

// --- Comments ---

const commentColumns = `id::text, task_id::text, content, author, created_at`

func scanComment(row pgx.Row) (*Comment, error) {
	c := &Comment{}
	if err := row.Scan(&c.ID, &c.TaskID, &c.Content, &c.Author, &c.Timestamp); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	return c, nil
}

// CreateComment resolves the parent task's project (needed to claim a seq)
// and inserts the comment in the same transaction — if the task doesn't
// exist, this returns ErrNotFound instead of a FK violation.
func (s *Store) CreateComment(ctx context.Context, c *Comment, actor string) (*Comment, []StoredEvent, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return nil, nil, err
	}
	defer tx.Rollback(ctx)

	var projectID string
	if err := tx.QueryRow(ctx, `SELECT project_id::text FROM tasks WHERE id = $1::uuid`, c.TaskID).Scan(&projectID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil, ErrNotFound
		}
		return nil, nil, err
	}

	row := tx.QueryRow(ctx, `
		INSERT INTO comments (task_id, content, author)
		VALUES ($1::uuid, $2, $3)
		RETURNING `+commentColumns,
		c.TaskID, c.Content, c.Author,
	)
	created, err := scanComment(row)
	if err != nil {
		return nil, nil, err
	}

	ev, err := recordEvent(ctx, tx, projectID, EventCommentAdded, CommentAddedPayload{Comment: created}, actor)
	if err != nil {
		return nil, nil, err
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, nil, err
	}
	return created, []StoredEvent{ev}, nil
}

func (s *Store) ListCommentsByTask(ctx context.Context, taskID string) ([]*Comment, error) {
	rows, err := s.pool.Query(ctx, `SELECT `+commentColumns+` FROM comments WHERE task_id = $1::uuid ORDER BY created_at`, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*Comment{}
	for rows.Next() {
		c, err := scanComment(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// DeleteComment resolves the parent task/project before deleting — that
// context is only recoverable via the FK join before the row is gone.
func (s *Store) DeleteComment(ctx context.Context, id string, actor string) (taskID, projectID string, events []StoredEvent, err error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return "", "", nil, err
	}
	defer tx.Rollback(ctx)

	if err := tx.QueryRow(ctx, `
		SELECT c.task_id::text, t.project_id::text
		FROM comments c JOIN tasks t ON t.id = c.task_id
		WHERE c.id = $1::uuid`, id,
	).Scan(&taskID, &projectID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return "", "", nil, ErrNotFound
		}
		return "", "", nil, err
	}

	if _, err := tx.Exec(ctx, `DELETE FROM comments WHERE id = $1::uuid`, id); err != nil {
		return "", "", nil, err
	}

	ev, err := recordEvent(ctx, tx, projectID, EventCommentDeleted, CommentDeletedPayload{CommentID: id, TaskID: taskID}, actor)
	if err != nil {
		return "", "", nil, err
	}

	if err := tx.Commit(ctx); err != nil {
		return "", "", nil, err
	}
	return taskID, projectID, []StoredEvent{ev}, nil
}
